### ISSUE TITLE
Error: Service to sync not found

### ISSUE THREAD

**Issue by boredazfcuk** [fabrizio2210/Docker_Volume_Synchronizator#4]
Hi,

I've tried running this Docker service (https://hub.docker.com/r/fabrizio2210/docker_volume_synchronizer) as I want to sync two data volumes, but ran into and error. In the logs I can see:
```
++ service=core_sync_squid
++ '[' -z core_sync_squid ']'
+++ findValueByLabel core_sync_squid async.service
+++ _my_service=core_sync_squid
+++ _label=async.service
++++ docker service ls --format '{{print .Name}}'
+++ for _service in $(docker service ls --format '{{print .Name}}')
+++ '[' core_sync_squid == core_squid ']'
+++ for _service in $(docker service ls --format '{{print .Name}}')
+++ '[' core_sync_squid == core_sync_squid ']'
+++ docker service inspect core_sync_squid '--format={{ index .Spec.Labels "async.service"}}'
+ set +x
+++ return
++ serviceToSync=
++ '[' -z '' ']'
++ echo 'Service to sync not found'
Service to sync not found
++ exit 2
cat: '/var/run/*.pid': No such file or directory
```
If I run this command from the command prompt:
```
docker service inspect core_sync_squid '--format={{ index .Spec.Labels "async.service"}}'
```
I get no results, which I would expect to see as it replicates the log. However, if I run:
```
docker service inspect core_sync_squid  --format="{{ index .Spec.TaskTemplate.ContainerSpec.Labels \"async.service\" }}"
```
then it returns :
```
squid
```
which is what I think the script is expecting to see. So, I think that there may be an error on line 253, of src/lib.sh could be incorrect.

I've tried changing this, and building the docker container locally, but a native build on ARM hardware fails at `RUN [ "cross-build-start" ]` with an exec error, so presumably this is incorrect architecture.

If I run the build on my amd64 hardware, it compiles successfully, but I get the same exec error when the node is deployed to the ARM hardware I'm running it on.

Any help would be greatly appreciated.

**Comment by fabrizio2210** [comment]
Hi boredazfcuk,
Thank you for your interest.
I can see there are two questions, so I divided in two answers. 

**Answer for the error:**
It seems it is not able to find the label `async.service` defined in the `core_sync_squid` service. How did you define the service? Can I see the stack file? If you found the label using the query `Spec.TaskTemplate.ContainerSpec.Labels` I can suppose that either you put the label in the wrong section, or you deployed the service as a simple container or without a stack. Or maybe the position of the label inside the "inspect format" is changed.


**Answer for compiling:**
There are 2 files for compiling, one is for x86_64 the other one is for arm. If you want to compile for x86_64 use `/docker/x86_64/Dockerfile` on a x86_64 platform (your amd64 is ok).
Compiling for arm is slighter more complicated, there is the file `docker/armv7hf/Dockerfile` but as you noticed there are two instructions `cross-build`. These two commands are needed to compile the image on an x86_64 arch with a result image for arm.This because normally I don't compile on arm directly, but I use online services (e.g. Dockerhub, Travis...) in order to compile. These services are normally x86_64.
So, if you want compile for arm on arm, remove the `[cross-build-start]` and `[cross-build-end]` from `docker/armv7hf/Dockerfile`.

**Comment by boredazfcuk** [comment]
Hi, thanks for taking a look at this for me.

For the error, I'm creating the label directly under the service name, like this:
```
   sync_core:
      image: fabrizio2210/docker_volume_synchronizer
      deploy:
         mode: global
      labels:
          - async.service=core
      volumes:
         - core_config:/config
         - core_data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      environment:
         - CSYNC2_KEY=<key>
```
It's definitely inside a stack, as I'm using `docker stack deploy` to create it and have verified this in the Portainer GUI I'm using.

In regards to compiling, I did try removing the two cross-build sections from the Dockerfile, but it still didn't work. I also changed the Docker version number (I'm on 19.x), just in case, but that didn't work either.

~I am using the buildx plugin to build the ARM image. This runs on AMD64, but uses QEMU to emulate ARM and then compiles inside that environment.~ Just double checked, it's just the standard `docker build` I'm using.

I've just got to head out to work so I can't get the exact error that was generated. Once I get there I'll connect back to my home server, kick off another build, and post results.

**Comment by boredazfcuk** [comment]
On my AMD64 machine, I build with:
```
docker build -f docker/armv7hf/Dockerfile --tag registry.domain.local:5001/docker_volume_sync .
```
With Dockerfile contents:
```
FROM balenalib/armv7hf-debian
MAINTAINER fabrizio2210
ENV DOCKERVERSION=19.03.12
ENV DOCKERARCH=armhf

RUN [ "cross-build-start" ]

RUN apt-get update && apt-get install -y csync2 lsyncd sed curl procps iputils-ping && apt-get clean

RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz

COPY src/* /usr/local/bin/

VOLUME ["/etc", "/var/lib/csync2"]

RUN [ "cross-build-end" ]

CMD /usr/local/bin/wrapper.sh
```
When the service is deployed to the ARM hardware, it just reports:
```
unsupported platform on 1 node
```
If I build on the ARM hardware (changing the tag so I can be certain):
```
docker build -f docker/armv7hf/Dockerfile --tag registry.domain.local:5001/vol_sync_arm .
```
With Dockerfile:
```
FROM balenalib/armv7hf-debian
MAINTAINER fabrizio2210
ENV DOCKERVERSION=19.03.12
ENV DOCKERARCH=armhf

RUN apt-get update && apt-get install -y csync2 lsyncd sed curl procps iputils-ping && apt-get clean

RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz

COPY src/* /usr/local/bin/

VOLUME ["/etc", "/var/lib/csync2"]

CMD /usr/local/bin/wrapper.sh
```

Then I get the same `unsupported platform on 1 node` error when deploying to the service.

**Comment by boredazfcuk** [comment]
Hi,

I've just tried building a multi-arch image (AMD64, ARM32v7 and ARM64v8) using the buildx plugin and I've seen this in the logs:
```
 => [linux/amd64 4/6] RUN curl -fsSLO https://download.docker.com/linux/static/stable/armhf/docker-19.03.12.tgz     && tar xzvf docker-19.03.12.tgz --strip 1 -C /usr/local/bin docker/docker     && rm d  70.3s
 => [linux/arm/v7 4/6] RUN curl -fsSLO https://download.docker.com/linux/static/stable/armhf/docker-19.03.12.tgz     && tar xzvf docker-19.03.12.tgz --strip 1 -C /usr/local/bin docker/docker     && rm   67.6s
 => [linux/arm64 4/6] RUN curl -fsSLO https://download.docker.com/linux/static/stable/armhf/docker-19.03.12.tgz     && tar xzvf docker-19.03.12.tgz --strip 1 -C /usr/local/bin docker/docker     && rm d  66.4s
```
I'm guessing this is why there's I get the "unsupported platform on 1 node" when the standard docker build is run, presumably curl is downloading `https://download.docker.com/linux/static/stable/amd64/docker-19.03.12.tgz`

I'll keep digging.

**Comment by boredazfcuk** [comment]
Urgh... I've figured out why it's not seeing label... My indentation is wrong, so it was creating a container label instead of a service label:

```
   sync_core:
      image: fabrizio2210/docker_volume_synchronizer
      deploy:
         mode: global
      labels:
          - async.service=core
      volumes:
         - core_config:/config
         - core_data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      environment:
         - CSYNC2_KEY=<key>
```
should be
```
   sync_core:
      image: fabrizio2210/docker_volume_synchronizer
      deploy:
         mode: global
         labels:
             - async.service=core
      volumes:
         - core_config:/config
         - core_data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      environment:
         - CSYNC2_KEY=<key>
```

Sorry for wasting your time...
